name = "TidierDates"
uuid = "20186a3f-b5d3-468e-823e-77aae96fe2d8"
authors = ["Daniel Rizk & Contributors"]
version = "0.2.3"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
Reexport = "0.2, 1"
julia = "1.6"
TimeZones = "1.17"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
