name = "TidierDates"
uuid = "20186a3f-b5d3-468e-823e-77aae96fe2d8"
authors = ["Daniel Rizk"]
version = "1.0.0-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
